from enum import Enum

class Icon(str, Enum):
    HAMMER = "hammer"
    WATER = "water"
    RELIGION = "religion"
    OPERA = "opera"
    CAMEL = "camel"
    TOWER = "tower"
    MARKET = "market"
    BARREL = "barrel"
    IRON = "iron"
    MORTAR = "mortar"
    LIGHTNING = "lightning"
    TORCH = "torch"
    TARGET = "target"
    LAMP = "lamp"
    SAW = "saw"
    PLANETS = "planets"
    SCALES = "scales"
    BOOK = "book"
    LIBRARY = "library"
    SCROLL = "scroll"
    LYRE = "lyre"
    FEATHER = "feather"
    FORT = "fort"
    HELMET = "helmet"
