---
config:
  class:
    hideEmptyMembersBox: true
  layout: elk
---
classDiagram
    class loader {
        load_cards(era: int, player_number: int) -> list[Card]
    }
    loader ..> Card
    loader ..> Card_Type
    loader ..> Resource
    loader ..> Effect
    loader ..> Icon

    class Game {
        decks: tuple[Deck]
        players: list[Player]
        discard_pile: Pile
        \_\_init\_\_(players: list[Player])
        run()
    }
    Game ..> Player
    Game ..> Deck
    Game ..> Pile

    class Player {
        hand: list[Card]
        city: City
        \_\_init\_\_(strat: Strategy)
        execute_turn(list[Player])
    }
    Player ..> Strategy
    Player ..> City
    Player ..> Card

    class Strategy {
        %% \_\_init\_\_()
    }

    class Deck {
        \_\_init\_\_(cards: list[Card])
        draw()
    }
    Deck ..> Card

    class Pile {
        \_\_init\_\_()
        cards: list[Card]
    }
    Pile ..> Card

    class Card {
        name: str
        type: Card_Type
        effect: Effect
        cost: list[Resource]
        give_icon: list[Icon]
        require_icon: Icon | None
        \_\_init\_\_(name, type, effect, cost, give_icon, require_icon)
    }
    Card ..> Effect
    Card ..> Resource
    Card ..> Icon

    class Card_Type {
      RAW_MATERIAL
      MANUFACTURED_GOOD
      CIVIC_STRUCTURE
      COMMERCIAL_STRUCTURE
      MILITARY_STRUCTURE
      SCIENTIFIC_STRUCTURE
      GUILD
    }
    Card_Type ..> Enum

    class Icon {
      HAMMER
      WATER
      RELIGION
      OPERA
      CAMEL
      LIGHTHOUSE
      MARKET
      BARREL
      IRON
      MORTAR
      LIGHTNING
      TORCH
      TARGET
      LAMP
      SAW
      PLANETS
      SCALES
      BOOK
      LIBRARY
      SCROLL
      LYRE
      FEATHER
      FORT
      HELMET
    }
    Icon ..> Enum

    class Resource {
      WOOD
      ORE
      CLAY
      BRICK
      STONE
      GLASS
      PAPYRUS
      TEXTILES
    }
    Resource ..> Enum

    class City {
        name: str
        wonder: Wonder
        money: int
        war_points: int
        cards: list[Card]
        productions: list[Production]
        \_\_init\_\_(name: str, wonder: Wonder, base_resource: Resource)
    }
    City ..> Card
    City ..> Wonder
    City ..> Resource
    City ..> Production

    class Production {
        product: list[list[Resource]]
        \_\_init\_\_(product: list[list[Resource]])
    }
    Production ..> Resource

    class Wonder {
        current_stage: int
        stage_effects: list[Effect]
        \_\_init\_\_(stage_effects: list[Effect])
    }
    Wonder ..> Effect

    class Effect {
        \_\_init\_\_(on_play, on_game_end)
        on_play(game: Game, owner: Player)
        on_game_end(game: Game, owner: Player)
    }
    Effect ..> Game
    Effect ..> Player

